<?php

namespace PaymentSystem\Laravel\Stripe\Repositories;

use EventSauce\EventSourcing\AggregateRootId;
use EventSauce\EventSourcing\ClassNameInflector;
use EventSauce\EventSourcing\EventSourcedAggregateRootRepository;
use EventSauce\EventSourcing\MessageDecorator;
use EventSauce\EventSourcing\MessageDispatcher;
use EventSauce\EventSourcing\MessageRepository;
use PaymentSystem\Stripe\RefundAggregateRoot;
use PaymentSystem\Stripe\Repositories\StripeRefundRepositoryInterface;

/**
 * @extends EventSourcedAggregateRootRepository<RefundAggregateRoot>
 */
class StripeRefundRepository extends EventSourcedAggregateRootRepository implements StripeRefundRepositoryInterface
{
    public function __construct(
        MessageRepository $messageRepository,
        ?MessageDispatcher $dispatcher = null,
        ?MessageDecorator $decorator = null,
        ?ClassNameInflector $classNameInflector = null
    ) {
        parent::__construct(RefundAggregateRoot::class, $messageRepository, $dispatcher, $decorator, $classNameInflector);
    }

    public function retrieve(AggregateRootId $aggregateRootId): RefundAggregateRoot
    {
        return parent::retrieve($aggregateRootId); // TODO: Change the autogenerated stub
    }
}
