<?php

namespace PaymentSystem\Laravel\Stripe\Repositories;


use EventSauce\EventSourcing\AggregateRootId;
use EventSauce\EventSourcing\ClassNameInflector;
use EventSauce\EventSourcing\EventSourcedAggregateRootRepository;
use EventSauce\EventSourcing\MessageDecorator;
use EventSauce\EventSourcing\MessageDispatcher;
use EventSauce\EventSourcing\MessageRepository;
use PaymentSystem\Stripe\PaymentIntentAggregateRoot;
use PaymentSystem\Stripe\Repositories\StripePaymentIntentRepositoryInterface;

/**
 * @extends EventSourcedAggregateRootRepository<PaymentIntentAggregateRoot>
 */
class StripePaymentIntentRepository extends EventSourcedAggregateRootRepository implements StripePaymentIntentRepositoryInterface
{
    public function __construct(
        MessageRepository $messageRepository,
        ?MessageDispatcher $dispatcher = null,
        ?MessageDecorator $decorator = null,
        ?ClassNameInflector $classNameInflector = null
    ) {
        parent::__construct(PaymentIntentAggregateRoot::class, $messageRepository, $dispatcher, $decorator, $classNameInflector);
    }

    public function retrieve(AggregateRootId $aggregateRootId): PaymentIntentAggregateRoot
    {
        return parent::retrieve($aggregateRootId); // TODO: Change the autogenerated stub
    }
}
